/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package presentacion;

import javax.swing.JComboBox;
import dominio.*;

/**
 *
 * @author docenteFI
 */
public class JFrameCalculador extends javax.swing.JFrame {

    private Calculador _calc;
    /**
     * Creates new form JFrameCalculador
     */
    public JFrameCalculador() {
        initComponents();
        
        //Nota: El codigo de instanciacion del JFrame tiene
        //que ir luego del initComponents();
    }
    
    public JFrameCalculador(Calculador modelo)
    {
        initComponents();
        InitCmbOpciones();
        AgregarEventosAControles();
        this._calc = modelo;
    }
    
    private void AgregarEventosAControles()
    {
        //Genero el controlador para el boton Add
        
         jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
         
        //Genero el controlador para el combo de operaciones
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
    }
            
           
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jbtnAdd = new javax.swing.JButton();
        jlblDisplay = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jlblDisplayResult = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Input");

        jbtnAdd.setText("Add");

        jlblDisplay.setText("Valores elegidos");

        jLabel2.setText("Resultado");

        jlblDisplayResult.setText("Display resultado");

        jLabel3.setText("Calcular");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jlblDisplayResult, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jlblDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                        .addComponent(jTextField1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbtnAdd))
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jlblDisplayResult)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InitCmbOpciones()
    {
        //Agrego las operaciones que se pueden hacer con los numeros ingresados
        this.jComboBox1.addItem("- Seleccionar un valor - ");
        this.jComboBox1.addItem("1 - Buscar el Mayor");
        this.jComboBox1.addItem("2 - Contar los pares");
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        
        //Este es el controlador del combo box de operaciones
        JComboBox cmb = (JComboBox) evt.getSource();
        String opcion = cmb.getSelectedItem().toString();

        if (!opcion.equals("- Seleccionar un valor - ")) {
            //aca hay que procesar
            Integer resultado = 0;

            if (opcion.equals("1 - Buscar el Mayor")) {
                resultado = this._calc.buscarElMayor();
            }

            if (opcion.equals("2 - Contar los pares")) {
                resultado = this._calc.contarLosPares();
            }

            this.jlblDisplayResult.setText("El resultado de la operacion es: " + resultado );
        }
    }                                          

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {                                        
        
        //Este es el controlador del boton Add que pasa los
        //valores al dominio
        Integer x = Integer.parseInt(
            this.jTextField1.getText());

        this._calc.SetValor(x);

        this.jlblDisplay.setText(this._calc.toString());
        this.jTextField1.setText("");

    }      
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JLabel jlblDisplay;
    private javax.swing.JLabel jlblDisplayResult;
    // End of variables declaration//GEN-END:variables
}
