/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import dominio.Modelo;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

/**
 *
 * @author Santiago
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private BarraMenu barraDeMenu;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        inicializar();
    }
    
    private void inicializar()
    {
        //aca caracterizo el formulario y configuro todo para iniciar
        //cerrar ejecucion de contexto
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
       
        //inicializar variables
        this.barraDeMenu = new BarraMenu();
        
        //enlazar elementos
        this.setJMenuBar(this.barraDeMenu);

        this.agregarAccionesMenu();
        
        //configuracion de la ventana: tamaño fijo
        //this.setSize(new Dimension(300,400));
        
        //configuracion a pantalla completa
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        this.setVisible(true);
    }
    
    //Agrego las acciones correspondientes al menu de la aplicacion
    public void agregarAccionesMenu(){
        ActionListener al = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ejecutarAccionMenu(((Component)e.getSource()).getName());
            }
        };
        for (int i = 0; i < this.barraDeMenu.getComponents().length; i++) {
            JMenu menu = this.barraDeMenu.getMenu(i);
            
            for (int j = 0; j < menu.getItemCount(); j++) {
                menu.getItem(j).addActionListener(al);
            }
        }
    }
    
    //analizo que opcion fue seleccionada y disparo el evento
    private void ejecutarAccionMenu(String action) {
        switch(action)
        {
            case "NuevaPelicula":
                this.initNuevaPelicula();
                break;
            case "ListadoAlfabetico":
                this.initListadoAlfabetico();
                break;
            default:
                break;
        }
    }
    
    
    private void initNuevaPelicula()
    {
        PeliculaFrm frmAgregarPelicula = new PeliculaFrm();
        
        ActionListener eventoAgregarPelicula = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                PeliculaFrm p = (PeliculaFrm)((Component)e.getSource()).getParent();
                Modelo.GetInstancia().AgregarPelicula(p.GetPelicula());
                p.LimpiarPantalla();
            }
        };
        
        frmAgregarPelicula.agregarAccionGuardar(eventoAgregarPelicula);
        agregarVentana(frmAgregarPelicula);
    }
    
    private void initListadoAlfabetico()
    {
        ListadoPeliculasFrm frmLisatdoPeliculas = new ListadoPeliculasFrm();
        agregarVentana(frmLisatdoPeliculas);
        frmLisatdoPeliculas.Actualizar(Modelo.GetInstancia().getListadoPeliculasOrdenado());
    }
    
    //Aca pongo en la ventana cada nuevo panel
    public void agregarVentana(JPanel ventana){
        this.getContentPane().removeAll(); //borro todos los paneles
        this.getContentPane().add(ventana); //agrego el nuevo
        
        ventana.setSize(new Dimension(
           ventana.getParent().getWidth(),
           ventana.getParent().getHeight())); 
                
        this.getContentPane().repaint(); //re dibujo el panel principal
        this.getContentPane().revalidate(); //actualizo punteros
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
