/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorListaUsurios;
import controlador.ListaUsuarios;
import java.util.ArrayList;
import modelo.Usuario;

/**
 *
 * @author docenteFI
 */
public class ListaUsuariosV1 extends javax.swing.JDialog implements ListaUsuarios{

    /**
     * Creates new form ListaUsuariosV1
     */
    private ControladorListaUsurios controlador;
            
    public ListaUsuariosV1(java.awt.Frame parent, boolean modal,Usuario logueado) {
        super(parent, modal);
        initComponents();
        controlador=new ControladorListaUsurios(logueado,this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jScrollPane1.setViewportView(lista);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 20, 330, 250);

        setBounds(0, 0, 416, 338);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        controlador.logout();
    }//GEN-LAST:event_formWindowClosing

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lista;
    // End of variables declaration//GEN-END:variables

    

    @Override
    public void mostarUsuarios(ArrayList<Usuario> l) {
        lista.setListData(l.toArray());
    }
}
