/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorLogin;
import controlador.Login;
import modelo.Usuario;

/**
 *
 * @author docenteFI
 */
public class LoginV2 extends javax.swing.JDialog implements Login{

    /**
     * Creates new form LoginV2
     */
    private ControladorLogin controlador;
    public LoginV2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controlador = new ControladorLogin(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        datos = new javax.swing.JTextField();
        estado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Usuario y password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 50, 100, 30);

        datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosActionPerformed(evt);
            }
        });
        getContentPane().add(datos);
        datos.setBounds(130, 50, 220, 30);

        estado.setText("Estado:");
        getContentPane().add(estado);
        estado.setBounds(20, 100, 340, 20);

        setBounds(0, 0, 416, 179);
    }// </editor-fold>//GEN-END:initComponents

    private void datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosActionPerformed
        // TODO add your handling code here:
        String[] str = datos.getText().split(" ");
        controlador.login(str[0], str[1]);
    }//GEN-LAST:event_datosActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField datos;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarErrorLogin() {
        estado.setText("Login Incorrecto");
    }

    @Override
    public void ingresar(Usuario logueado) {
        //JOptionPane.showMessageDialog(this,"Bienvenido");
        dispose();
        new VistaNumerosV1(null,false,logueado).setVisible(true);
        new VistaNumerosV2(null,false,logueado).setVisible(true);
    }

    @Override
    public void habilitar(boolean b) {
         datos.setEnabled(b);
    }
}
