/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Fachada;

/**
 *
 * @author docenteFI
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crear = new javax.swing.JButton();
        deshabilitar = new javax.swing.JButton();
        habilitar = new javax.swing.JButton();
        masNumeros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        crear.setText("Crear Interfaz para login");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        getContentPane().add(crear);
        crear.setBounds(100, 90, 200, 60);

        deshabilitar.setText("Deshabilitar Logins");
        deshabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deshabilitarActionPerformed(evt);
            }
        });
        getContentPane().add(deshabilitar);
        deshabilitar.setBounds(100, 170, 200, 90);

        habilitar.setText("Habilitar Login");
        habilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habilitarActionPerformed(evt);
            }
        });
        getContentPane().add(habilitar);
        habilitar.setBounds(110, 290, 180, 60);

        masNumeros.setText("Mas numeros");
        masNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masNumerosActionPerformed(evt);
            }
        });
        getContentPane().add(masNumeros);
        masNumeros.setBounds(110, 380, 190, 60);

        setBounds(0, 0, 416, 566);
    }// </editor-fold>//GEN-END:initComponents

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        // TODO add your handling code here:
        new LoginV1(null,false).setVisible(true);
    }//GEN-LAST:event_crearActionPerformed

    private void deshabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deshabilitarActionPerformed
        // TODO add your handling code here:
        Fachada.getInstancia().deshabilitar();
    }//GEN-LAST:event_deshabilitarActionPerformed

    private void habilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habilitarActionPerformed
        // TODO add your handling code here:
        Fachada.getInstancia().habilitar();
    }//GEN-LAST:event_habilitarActionPerformed

    private void masNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masNumerosActionPerformed
        // TODO add your handling code here:
        Fachada.getInstancia().masNumeros();
    }//GEN-LAST:event_masNumerosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crear;
    private javax.swing.JButton deshabilitar;
    private javax.swing.JButton habilitar;
    private javax.swing.JButton masNumeros;
    // End of variables declaration//GEN-END:variables
}
