/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorNumeros;
import controlador.VistaNumeros;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import modelo.Numero;
import modelo.Usuario;

/**
 *
 * @author docenteFI
 */
public class VistaNumerosV1 extends javax.swing.JDialog implements VistaNumeros,ActionListener{

    /**
     * Creates new form VistaNumeros
     */
    private ControladorNumeros controlador;
    private JSplitPane panel = new JSplitPane();
    
    public VistaNumerosV1(java.awt.Frame parent, boolean modal,Usuario u) {
        super(parent, modal);
        initComponents();
        panel.setTopComponent(new PanelDatos());
        setContentPane(panel);
        panel.setOrientation(JSplitPane.VERTICAL_SPLIT);
        controlador = new ControladorNumeros(this,u);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    @Override
    public void mostrarNumeros(ArrayList<Numero> numeros) {
        PanelNumeros panelN = new PanelNumeros(numeros,this);
        panel.setBottomComponent(panelN);
        validate();
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        Boton origen = (Boton)e.getSource();
        controlador.marcar(origen.getNumero());
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
